# Generated by Django 4.0.7 on 2022-09-29 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('extra', '0002_offerproduct_offercategory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='discount',
            new_name='discount_percentage',
        ),
    ]
