# Generated by Django 4.0.7 on 2022-09-29 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_options_alter_category_cat_image'),
        ('products', '0003_product_discount'),
        ('extra', '0003_rename_discount_coupon_discount_percentage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OfferCategory',
            new_name='Categoryoffer',
        ),
        migrations.RenameModel(
            old_name='OfferProduct',
            new_name='Productoffer',
        ),
    ]
